from enum import Enum


class Signal(str, Enum):
	
	ADD_LIKE = "ADD_LIKE"
	ADD_LIKE_AND_REMOVE_DISLIKE = "ADD_LIKE_AND_REMOVE_DISLIKE"
	REMOVE_LIKE = "REMOVE_LIKE"

	ADD_DISLIKE = "ADD_DISLIKE"
	ADD_DISLIKE_AND_REMOVE_LIKE = "ADD_DISLIKE_AND_REMOVE_LIKE"
	REMOVE_DISLIKE = "REMOVE_DISLIKE"