
// polls
export const GET_POLLS = "GET_POLLS";
export const DELETE_POLL = "DELETE_POLL";
export const ADD_POLL = "ADD_POLL";
export const SET_POLL_LIKES_AND_DISLIKES = "SET_POLL_LIKES_AND_DISLIKES";
export const HANDLE_VOTE = "HANDLE_VOTE";
export const GET_USER_VOTES = "GET_USER_VOTES";
export const GET_USER_LIKES = "GET_USER_LIKES";
export const GET_USER_DISLIKES = "GET_USER_DISLIKES";
export const REMOVE_USER_VOTES = "REMOVE_USER_VOTES";
export const REMOVE_USER_LIKES = "REMOVE_USER_LIKES";
export const REMOVE_USER_DISLIKES = "REMOVE_USER_DISLIKES";
export const INCREMENT_POLL_LIKES = "INCREMENT_POLL_LIKES";
export const DECREMENT_POLL_LIKES = "DECREMENT_POLL_LIKES";
export const INCREMENT_POLL_DISLIKES = "INCREMENT_POLL_DISLIKES";
export const DECREMENT_POLL_DISLIKES = "DECREMENT_POLL_DISLIKES"


// comments
export const GET_COMMENTS = "GET_COMMENTS";
export const ADD_COMMENT = "ADD_COMMENT";
export const SET_COMMENT_LIKES_AND_DISLIKES = "SET_COMMENT_LIKES_AND_DISLIKES";
export const GET_USER_COMMENT_LIKES = "GET_USER_COMMENT_LIKES";
export const GET_USER_COMMENT_DISLIKES = "GET_USER_COMMENT_DISLIKES";
export const INCREMENT_COMMENT_LIKES = "INCREMENT_COMMENT_LIKES";
export const DECREMENT_COMMENT_LIKES = "DECREMENT_COMMENT_LIKES";
export const INCREMENT_COMMENT_DISLIKES = "INCREMENT_COMMENT_DISLIKES";
export const DECREMENT_COMMENT_DISLIKES = "DECREMENT_COMMENT_DISLIKES"


// auth
export const USER_AUTHENTICATED = "USER_AUTHENTICATED";
export const HANDLE_LOGOUT = "HANDLE_LOGOUT";
export const PASSWORD_RESET_REQUESTED = "PASSWORD_RESET_REQUESTED";
export const PASSWORD_RESET_CONFIRMED ='PASSWORD_RESET_CONFIRMED';
export const REGISTER_ACCOUNT_PENDING = "REGISTER_ACCOUNT_PENDING";
export const REGISTER_ACCOUNT_SUCCESS = "REGISTER_ACCOUNT_SUCCESS";
export const REGISTER_ACCOUNT_FAILURE = "REGISTER_ACCOUNT_FAILURE";
export const ACTIVATE_ACCOUNT_PENDING = 'ACTIVATE_ACCOUNT_PENDING';
export const ACTIVATE_ACCOUNT_SUCCESS = 'ACTIVATE_ACCOUNT_SUCCESS';


// errors 
export const GET_ERRORS = "GET_ERRORS"

// alerts
export const CREATE_MESSAGE = "CREATE_MESSAGE"

// users 
export const GET_USERS = "GET_USERS"
export const ADD_NEW_USER = "ADD_NEW_USER"