// signals 
export const ADD_LIKE = "ADD_LIKE";
export const ADD_LIKE_AND_REMOVE_DISLIKE = "ADD_LIKE_AND_REMOVE_DISLIKE";
export const REMOVE_LIKE = "REMOVE_LIKE";

export const ADD_DISLIKE = "ADD_DISLIKE";
export const ADD_DISLIKE_AND_REMOVE_LIKE = "ADD_DISLIKE_AND_REMOVE_LIKE";
export const REMOVE_DISLIKE = "REMOVE_DISLIKE";

// polls
export const GET_POLLS = "GET_POLLS";
export const DELETE_POLL = "DELETE_POLL";
export const ADD_POLL = "ADD_POLL";
export const HANDLE_VOTE = "HANDLE_VOTE";
export const GET_USER_VOTES = "GET_USER_VOTES";
export const GET_USER_LIKES = "GET_USER_LIKES";
export const GET_USER_DISLIKES = "GET_USER_DISLIKES";
export const REMOVE_USER_VOTES = "REMOVE_USER_VOTES";
export const REMOVE_USER_LIKES = "REMOVE_USER_LIKES";
export const REMOVE_USER_DISLIKES = "REMOVE_USER_DISLIKES";

// comments
export const GET_COMMENTS = "GET_COMMENTS";
export const ADD_COMMENT = "ADD_COMMENT";
export const GET_USER_COMMENT_LIKES = "GET_USER_COMMENT_LIKES";
export const GET_USER_COMMENT_DISLIKES = "GET_USER_COMMENT_DISLIKES";
export const ADD_LIKE_ON_COMMENT = "ADD_LIKE_ON_COMMENT";
export const ADD_LIKE_AND_REMOVE_DISLIKE_ON_COMMENT = "ADD_LIKE_AND_REMOVE_DISLIKE_ON_COMMENT";
export const REMOVE_LIKE_ON_COMMENT = "REMOVE_LIKE_ON_COMMENT";
export const ADD_DISLIKE_ON_COMMENT = "ADD_DISLIKE_ON_COMMENT";
export const ADD_DISLIKE_AND_REMOVE_LIKE_ON_COMMENT = "ADD_DISLIKE_AND_REMOVE_LIKE_ON_COMMENT";
export const REMOVE_DISLIKE_ON_COMMENT = "REMOVE_DISLIKE_ON_COMMENT";

// auth
export const USER_AUTHENTICATED = "USER_AUTHENTICATED";
export const HANDLE_LOGOUT = "HANDLE_LOGOUT";
export const PASSWORD_RESET_REQUESTED = "PASSWORD_RESET_REQUESTED";
export const PASSWORD_RESET_CONFIRMED ='PASSWORD_RESET_CONFIRMED';
export const REGISTER_ACCOUNT_PENDING = "REGISTER_ACCOUNT_PENDING";
export const REGISTER_ACCOUNT_SUCCESS = "REGISTER_ACCOUNT_SUCCESS";
export const REGISTER_ACCOUNT_FAILURE = "REGISTER_ACCOUNT_FAILURE";
export const ACTIVATE_ACCOUNT_PENDING = 'ACTIVATE_ACCOUNT_PENDING';
export const ACTIVATE_ACCOUNT_SUCCESS = 'ACTIVATE_ACCOUNT_SUCCESS';

// errors 
export const GET_ERRORS = "GET_ERRORS"

// alerts
export const CREATE_MESSAGE = "CREATE_MESSAGE"

// users 
export const GET_USERS = "GET_USERS"
export const ADD_NEW_USER = "ADD_NEW_USER"