# Generated by Django 3.0.5 on 2020-05-26 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20200518_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
