# Generated by Django 3.0.6 on 2020-08-02 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0006_auto_20200709_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='choice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Choice'),
        ),
        migrations.AlterUniqueTogether(
            name='dislike',
            unique_together={('poll', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('poll', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('poll', 'choice', 'user')},
        ),
    ]
